### ISSUE TITLE
[FR] 增加对 macOS 的支持

### ISSUE THREAD

**Issue by Lucas04-nhr** [BTMuli/ShufflePlay#1]
看到程序似乎是用 Flutter 写的，请问能否像 TeyvatGuide 一样增加 macOS 平台的构建或者提供 macOS 平台的构建方法呢?

**Comment by BTMuli** [comment]
Flutter 对于构建 macOS 的要求 [较为复杂](https://docs.flutter.cn/get-started/install/macos/)，我这边没有 macOS 的机子作为本地构建&测试环境，而且目前 ShufflePlay 仍处于早期~~太咕了导致的~~，这项议题的优先度较低。

**Comment by Lucas04-nhr** [comment]
我昨天尝试在本地构建，似乎需要提高target版本，处理一些依赖问题才能构建成功。如果有什么需要帮助的话我很乐意帮忙。

**Comment by BTMuli** [comment]
> 如果有什么需要帮助的话我很乐意帮忙。

657618889，~~懒得再建一个SP群了~~
